
export const EXERCISES = [
  // ── Chest ──────────────────────────────────────────────────────────────────
  { id:'ex001', name:'Barbell Bench Press',         muscle:'Chest',       movement:'push',  equipment:'Barbell',
    feel:'Deep stretch across the chest at the bottom; hard squeeze driving both pecs together as you press up.',
    cues:['Shoulder blades pinched together & down','Bar touches lower chest, not neck','Elbows ~45° from torso, not flared','Drive feet into floor for leg drive'],
    yt:'barbell bench press form tutorial' },
  { id:'ex002', name:'Incline Barbell Press',       muscle:'Chest',       movement:'push',  equipment:'Barbell',
    feel:'Stretch higher on the chest near the collarbone; squeeze in the upper pec at the top — not the front shoulder.',
    cues:['Bench 30–45°, not too steep','Bar to upper chest / clavicle area','Same scapular retraction as flat bench','Control descent — don\'t bounce'],
    yt:'incline barbell press form tutorial' },
  { id:'ex003', name:'Dumbbell Bench Press',        muscle:'Chest',       movement:'push',  equipment:'Dumbbell',
    feel:'A deeper chest stretch than barbell as elbows drop below the bench; squeeze the pecs together as dumbbells rise.',
    cues:['Let elbows drop slightly below bench','Dumbbells travel in slight arc, not straight up','Neutral wrists throughout','Pause at bottom for full stretch'],
    yt:'dumbbell bench press form tutorial' },
  { id:'ex004', name:'Push Up',                     muscle:'Chest',       movement:'push',  equipment:'Bodyweight',
    feel:'Chest stretched as you lower; imagine trying to pull your hands toward each other as you press — squeeze pecs at the top.',
    cues:['Body stays rigid like a plank','Elbows track ~45° from torso','Chest touches floor at bottom','Breathe out on the way up'],
    yt:'push up proper form tutorial' },
  { id:'ex005', name:'Incline Dumbbell Press',      muscle:'Chest',       movement:'push',  equipment:'Dumbbell',
    feel:'Upper chest opening wide at the bottom; a strong inward squeeze near the collarbone at the top.',
    cues:['Bench at 30–45° for upper chest emphasis','Dumbbells just outside shoulders at bottom','Drive up and slightly inward at top','Full range — let chest open at bottom'],
    yt:'incline dumbbell press form tutorial' },
  { id:'ex006', name:'Decline Barbell Press',       muscle:'Chest',       movement:'push',  equipment:'Barbell',
    feel:'Lower chest and the underside of the pecs stretching at the bottom; squeeze at the bottom of the chest as you press.',
    cues:['Feet secured before unracking','Bar to lower chest / sternum','Elbows track same as flat bench','Spotter recommended for heavy sets'],
    yt:'decline bench press form tutorial' },
  { id:'ex007', name:'Decline Dumbbell Press',      muscle:'Chest',       movement:'push',  equipment:'Dumbbell',
    feel:'Lower outer chest stretching at the bottom; squeeze the lower pecs together as dumbbells meet at the top.',
    cues:['Secure feet before starting','Lower chest / sternum target','Controlled descent, full stretch','Bring dumbbells together at top'],
    yt:'decline dumbbell press form tutorial' },
  { id:'ex008', name:'Cable Fly',                   muscle:'Chest',       movement:'push',  equipment:'Cable',
    feel:'A long open stretch across the chest as arms extend; constant cable tension then a hard inner-chest squeeze as hands come together.',
    cues:['Slight bend in elbows throughout — fixed','Think "hugging a barrel"','Squeeze pecs at peak contraction','Control the return — don\'t let cables pull you'],
    yt:'cable fly chest form tutorial' },
  { id:'ex009', name:'Dumbbell Fly',                muscle:'Chest',       movement:'push',  equipment:'Dumbbell',
    feel:'The deepest chest stretch of any exercise — pecs pulled wide at the bottom; squeeze them together at the top like hugging someone.',
    cues:['Slight elbow bend — don\'t straighten arms','Open chest wide at bottom','Squeeze at top but don\'t slam dumbbells','This is a stretch exercise — go light'],
    yt:'dumbbell fly form tutorial' },
  { id:'ex010', name:'Pec Deck',                    muscle:'Chest',       movement:'push',  equipment:'Machine',
    feel:'Constant pec activation throughout; a hard squeeze right across the centre of the chest when pads meet.',
    cues:['Forearms flat against pads','Squeeze chest fully at peak','Don\'t let elbows drift behind shoulder line','Slow, controlled return'],
    yt:'pec deck fly form tutorial' },
  { id:'ex011', name:'Machine Chest Press',         muscle:'Chest',       movement:'push',  equipment:'Machine',
    feel:'Mid-chest contraction as you press — feel it through the pecs, not the shoulders or triceps.',
    cues:['Adjust seat so handles are at chest height','Keep back against pad throughout','Don\'t lock out elbows fully','Control the negative'],
    yt:'machine chest press form tutorial' },
  { id:'ex012', name:'Smith Machine Bench Press',   muscle:'Chest',       movement:'push',  equipment:'Machine',
    feel:'Same as flat bench — stretch across the mid chest at the bottom, squeeze the pecs as you drive up.',
    cues:['Position body so bar tracks over lower chest','Rotate hooks to unrack safely','Treat like regular bench — same cues','Easier to control for beginners'],
    yt:'smith machine bench press form' },
  { id:'ex013', name:'Cable Crossover',             muscle:'Chest',       movement:'push',  equipment:'Cable',
    feel:'Inner chest squeeze as hands cross — the crossover position lets you feel the pec major contracting at its full range.',
    cues:['Set pulleys high for lower chest emphasis','Step forward with slight forward lean','Squeeze hands together in front of body','Keep elbows soft throughout'],
    yt:'cable crossover chest form tutorial' },
  { id:'ex014', name:'Chest Dips',                  muscle:'Chest',       movement:'push',  equipment:'Bodyweight',
    feel:'Deep lower-chest stretch as you dip; a full lower pec squeeze as you press back up — lean forward keeps it in the chest.',
    cues:['Lean forward to target chest over triceps','Go deep — upper arm parallel to floor','Keep elbows slightly flared, not pinned','Add weight once bodyweight feels easy'],
    yt:'chest dips form tutorial' },
  { id:'ex015', name:'Low Cable Fly',               muscle:'Chest',       movement:'push',  equipment:'Cable',
    feel:'Upper chest being pulled inward as you arc upward — clavicular head of the pec works hardest at the top.',
    cues:['Pulleys set at ankle height','Arc hands upward and together','Target upper chest / clavicular head','Squeeze hard at top contraction'],
    yt:'low cable fly upper chest form' },
  { id:'ex016', name:'High Cable Fly',              muscle:'Chest',       movement:'push',  equipment:'Cable',
    feel:'Lower chest squeeze as you arc hands down and together — feel it in the lower-outer pec.',
    cues:['Pulleys above head','Arc hands downward and together','Target lower chest','Slight forward lean for better stretch'],
    yt:'high cable fly lower chest form' },
  { id:'ex017', name:'Svend Press',                 muscle:'Chest',       movement:'push',  equipment:'Plate',
    feel:'Constant inner-chest squeeze throughout — the squeeze tension from pressing plates together should burn mid-chest the entire set.',
    cues:['Squeeze plates together hard throughout','Press out slowly while maintaining squeeze','Bring back slowly — squeeze harder on return','Great finisher for chest pump'],
    yt:'svend press chest form' },
  { id:'ex018', name:'Landmine Press',              muscle:'Chest',       movement:'push',  equipment:'Barbell',
    feel:'Upper chest and front shoulder — feel it especially through the upper inner chest at lockout.',
    cues:['Stand perpendicular or at slight angle','One hand grips the end of bar','Press at 45° angle — upper chest focus','Keep core tight throughout'],
    yt:'landmine press form tutorial' },
  { id:'ex019', name:'Wide Push Up',                muscle:'Chest',       movement:'push',  equipment:'Bodyweight',
    feel:'Outer chest stretched wide at the bottom; outer pec squeeze as you push back up.',
    cues:['Hands wider than shoulder width','This increases chest stretch at bottom','Elbows still track at ~45°, not 90°','Full chest-to-floor depth'],
    yt:'wide push up form tutorial' },
  { id:'ex020', name:'Diamond Push Up',             muscle:'Chest',       movement:'push',  equipment:'Bodyweight',
    feel:'Mostly triceps with inner chest — feel the back of the arm and a centre-chest squeeze at lockout.',
    cues:['Hands close together under sternum','This shifts emphasis to triceps','Keep body plank-rigid','Elbows track back alongside torso'],
    yt:'diamond push up form tutorial' },

  // ── Back ───────────────────────────────────────────────────────────────────
  { id:'ex021', name:'Deadlift',                    muscle:'Back',        movement:'hinge', equipment:'Barbell',
    feel:'Full posterior chain — lower back, glutes and hamstrings all working. At lockout feel your lats braced and glutes squeezed hard.',
    cues:['Hinge at hips — don\'t squat the weight up','Bar stays dragging against shins & thighs','Brace core hard before you pull','Lock hips out at top, don\'t hyperextend'],
    yt:'deadlift form tutorial beginners' },
  { id:'ex022', name:'Romanian Deadlift',           muscle:'Back',        movement:'hinge', equipment:'Barbell',
    feel:'A deep pulling stretch through the hamstrings as you hinge down; lower back and glutes engaging all the way back up.',
    cues:['Push hips backward — bar slides down thighs','Feel the hamstring stretch at bottom','Spine stays neutral throughout','Only go as low as your hamstrings allow'],
    yt:'romanian deadlift form tutorial' },
  { id:'ex023', name:'Trap Bar Deadlift',           muscle:'Back',        movement:'hinge', equipment:'Barbell',
    feel:'Quads and glutes during the drive up; lats and traps bracing throughout. More balanced than conventional — less lower back.',
    cues:['Grip handles, sit hips down like a squat-hinge hybrid','Chest up, neutral spine','Push floor away — not just pull up','Easier on lower back than conventional'],
    yt:'trap bar deadlift form tutorial' },
  { id:'ex024', name:'Sumo Deadlift',               muscle:'Back',        movement:'hinge', equipment:'Barbell',
    feel:'Inner thighs and glutes more than conventional — feel your hips driving forward and glutes squeezing hard at lockout.',
    cues:['Wide stance, toes angled out 30–60°','Push knees out along toe line','Bar stays over mid-foot','Pull slack out before pulling'],
    yt:'sumo deadlift form tutorial' },
  { id:'ex025', name:'Pull Up',                     muscle:'Back',        movement:'pull',  equipment:'Bodyweight',
    feel:'Lats (the "wings" under your armpits) pulling your elbows down — imagine putting your shoulder blades into your back pockets.',
    cues:['Start from dead hang, arms fully extended','Lead chest to bar — don\'t just chin over','Drive elbows down and back','Squeeze lats hard at top'],
    yt:'pull up form tutorial' },
  { id:'ex026', name:'Chin Up',                     muscle:'Back',        movement:'pull',  equipment:'Bodyweight',
    feel:'Lats and biceps together — stronger bicep involvement than pull-up; still feel the lats pulling elbows down to your sides.',
    cues:['Supinated grip (palms facing you) involves more biceps','Same as pull-up but slightly more bicep emphasis','Full dead hang at bottom','Chest to bar for full range'],
    yt:'chin up proper form tutorial' },
  { id:'ex027', name:'Lat Pulldown',                muscle:'Back',        movement:'pull',  equipment:'Cable',
    feel:'Lats pulling your elbows down — think elbows to your back pockets. Squeeze the lats hard when bar touches your chest.',
    cues:['Slight backward lean — not 45°','Pull bar to upper chest, not behind neck','Drive elbows down into pockets','Squeeze lats at bottom'],
    yt:'lat pulldown form tutorial' },
  { id:'ex028', name:'Wide Grip Lat Pulldown',      muscle:'Back',        movement:'pull',  equipment:'Cable',
    feel:'Lat width — feel the outer edges of your back working as elbows arc down and back.',
    cues:['Grip wider than shoulder width','Less range of motion — compensate with squeeze','Really focus on flaring lats at peak','Don\'t lean back excessively'],
    yt:'wide grip lat pulldown form' },
  { id:'ex029', name:'Close Grip Lat Pulldown',     muscle:'Back',        movement:'pull',  equipment:'Cable',
    feel:'Lower lats and biceps together — feel the elbows driving straight down to your hips through a full range.',
    cues:['Neutral grip handle or close grip','Elbows drive straight down to hips','Longer range of motion than wide grip','More bicep involvement'],
    yt:'close grip lat pulldown form tutorial' },
  { id:'ex030', name:'Seated Cable Row',            muscle:'Back',        movement:'pull',  equipment:'Cable',
    feel:'Mid-back and inner traps — feel your shoulder blades being pinched together and pulled back as you row.',
    cues:['Hinge back slightly at start','Pull handle to lower chest / navel','Squeeze shoulder blades together','Return with control — don\'t round forward'],
    yt:'seated cable row form tutorial' },
  { id:'ex031', name:'Barbell Row',                 muscle:'Back',        movement:'pull',  equipment:'Barbell',
    feel:'Mid-back, lats and rear delts — feel your elbows driving back and shoulder blades squeezing at the top.',
    cues:['Hinge forward ~45° — not upright','Pull bar to lower chest or upper navel','Elbows drive back, not flared wide','Keep lower back flat throughout'],
    yt:'barbell row form tutorial' },
  { id:'ex032', name:'Dumbbell Row',                muscle:'Back',        movement:'pull',  equipment:'Dumbbell',
    feel:'One side of your back at a time — lat, teres major and rear delt. Feel the elbow drive back and shoulder blade fully retract.',
    cues:['Brace on bench — flat back, not rounded','Pull dumbbell to hip, elbow drives back','Full stretch at bottom each rep','Don\'t rotate torso to cheat weight up'],
    yt:'dumbbell row form tutorial' },
  { id:'ex033', name:'T-Bar Row',                   muscle:'Back',        movement:'pull',  equipment:'Barbell',
    feel:'Mid-back and rhomboids — strong squeeze between the shoulder blades at the top of each rep.',
    cues:['Chest against pad (if chest-supported version)','Pull handles to chest','Drive elbows back and up','Squeeze rhomboids and mid-traps at top'],
    yt:'t-bar row form tutorial' },
  { id:'ex034', name:'Pendlay Row',                 muscle:'Back',        movement:'pull',  equipment:'Barbell',
    feel:'An explosive engagement of the entire upper back — feel all the mid-back and lat musculature fire hard from a dead stop.',
    cues:['Bar starts on floor each rep — explosive pull','Torso stays close to horizontal (not 45°)','Bar to lower chest','More power-focused than a regular row'],
    yt:'pendlay row form tutorial' },
  { id:'ex035', name:'Chest Supported Row',         muscle:'Back',        movement:'pull',  equipment:'Dumbbell',
    feel:'Pure back isolation with zero lower back compensation — feel the lats and mid-traps working cleanly as shoulder blades pinch together.',
    cues:['Chest on incline bench removes lower back stress','Let arms hang fully at bottom','Pull elbows back and together','Great for isolating back without fatigue compensation'],
    yt:'chest supported row form tutorial' },
  { id:'ex036', name:'Single Arm Cable Row',        muscle:'Back',        movement:'pull',  equipment:'Cable',
    feel:'A twisting contraction of the lat and mid-back — feel the shoulder blade fully retract at peak contraction.',
    cues:['Rotate torso slightly toward cable at start','Pull and rotate back — full contraction','One side at a time for symmetry focus','Keep hips squared'],
    yt:'single arm cable row form' },
  { id:'ex037', name:'Face Pull',                   muscle:'Back',        movement:'pull',  equipment:'Cable',
    feel:'Rear delts and external rotators — feel the back of your shoulder working as elbows flare high and hands pull toward your face.',
    cues:['Rope at face / upper-chest height','Pull to forehead — external rotation at end','Elbows stay high throughout','Great for rear delts and shoulder health'],
    yt:'face pull form tutorial' },
  { id:'ex038', name:'Reverse Fly',                 muscle:'Back',        movement:'pull',  equipment:'Dumbbell',
    feel:'Rear delts and mid-traps — feel the squeeze across the upper back as arms open wide to the sides.',
    cues:['Slight hinge forward','Arms arc out to sides — think "reverse hug"','Squeeze rear delts at top','Keep elbows soft, not locked'],
    yt:'reverse fly rear delt form tutorial' },
  { id:'ex039', name:'Straight Arm Pulldown',       muscle:'Back',        movement:'pull',  equipment:'Cable',
    feel:'Lat isolation only — arms stay straight so you feel only the side of your back, a strong burn from armpit to hip.',
    cues:['Arms stay straight throughout — no elbow bend','Push bar from shoulder height to hips','Feel lat stretch at top','Squeeze at bottom contraction'],
    yt:'straight arm pulldown form tutorial' },
  { id:'ex040', name:'Rack Pull',                   muscle:'Back',        movement:'hinge', equipment:'Barbell',
    feel:'Traps, lats and glutes heavily loaded — feel the upper back and traps bracing intensely at lockout.',
    cues:['Start from just below knee or mid-shin','Same cues as deadlift from that position','Lock hips out hard at top','Overload movement — use straps if needed'],
    yt:'rack pull form tutorial' },
  { id:'ex041', name:'Deficit Deadlift',            muscle:'Back',        movement:'hinge', equipment:'Barbell',
    feel:'Greater hamstring stretch at the very bottom before the pull — feel the posterior chain loaded deeper than a regular deadlift.',
    cues:['Stand on plate or raised surface','Increases range of motion at bottom','Requires more hip mobility than regular deadlift','Lower back under greater stress — start light'],
    yt:'deficit deadlift form tutorial' },
  { id:'ex042', name:'Paused Deadlift',             muscle:'Back',        movement:'hinge', equipment:'Barbell',
    feel:'Constant tension through the whole posterior chain during the pause — hamstrings, glutes and lats all held under load with no momentum.',
    cues:['Pause for 1–2 seconds just below knee','Eliminates momentum — builds true strength','Hold brace throughout the pause','Excellent for fixing sticking points'],
    yt:'paused deadlift form tutorial' },
  { id:'ex043', name:'Back Extension',              muscle:'Back',        movement:'hinge', equipment:'Machine',
    feel:'Lower back (erectors) contracting as you extend up; squeeze glutes at the top — if you feel it only in your lower back, add a glute squeeze.',
    cues:['Hips on pad, not waist','Lower with control until body is parallel','Extend up to neutral spine — don\'t hyperextend','Add plate to chest for progression'],
    yt:'back extension form tutorial' },
  { id:'ex044', name:'Hyperextension',              muscle:'Back',        movement:'hinge', equipment:'Bodyweight',
    feel:'Erectors and glutes — full extension should produce a strong glute and lower back contraction at the top.',
    cues:['Full range: drop torso down, extend up','Don\'t jerk or use momentum','Squeeze glutes at top','Bodyweight first — add load carefully'],
    yt:'hyperextension form tutorial' },
  { id:'ex045', name:'Good Morning',                muscle:'Back',        movement:'hinge', equipment:'Barbell',
    feel:'Hamstrings and lower back — deep hamstring stretch as you hinge forward; lower back engaged all the way through the return.',
    cues:['Bar on upper traps like a squat','Hinge at hips — same as RDL but bar is on back','Feel hamstring tension at bottom','Keep chest up, back flat'],
    yt:'good morning exercise form tutorial' },
  { id:'ex046', name:'TRX Row',                     muscle:'Back',        movement:'pull',  equipment:'Bodyweight',
    feel:'Mid-back and lats — feel your body weight being pulled through the back as you pull your chest up to your hands.',
    cues:['Body stays plank-rigid throughout','Pull chest to hands — not chin over','The more horizontal you are, the harder it is','Drive elbows back at top'],
    yt:'TRX row form tutorial' },
  { id:'ex047', name:'Band Pull Apart',             muscle:'Back',        movement:'pull',  equipment:'Band',
    feel:'Rear delts and mid-traps — feel the back of your shoulder and between your shoulder blades as the band spreads wide.',
    cues:['Straight arms at shoulder height','Pull band apart to full arm extension','Squeeze rear delts and mid-back at peak','Great warm-up or finisher for shoulder health'],
    yt:'band pull apart form tutorial' },
  { id:'ex048', name:'Seal Row',                    muscle:'Back',        movement:'pull',  equipment:'Barbell',
    feel:'Pure mid-back and lat isolation — no lower back compensation, just elbows driving back and shoulder blades squeezing together.',
    cues:['Lie prone on elevated bench','Bar hangs freely — full stretch each rep','Pull to chest height','Zero lower back involvement — pure back isolation'],
    yt:'seal row form tutorial' },
  { id:'ex049', name:'Meadows Row',                 muscle:'Back',        movement:'pull',  equipment:'Barbell',
    feel:'Lower lat and outer back — feel it pulling from the side of your torso, more lower-lat insertion than a standard row.',
    cues:['Straddle end of landmine bar','Pull end of bar to hip in arc','Great for lat width and lower lat insertion','Stance perpendicular to bar'],
    yt:'meadows row form tutorial' },
  { id:'ex050', name:'Jefferson Curl',              muscle:'Back',        movement:'hinge', equipment:'Barbell',
    feel:'A lengthening sensation through the entire spine and hamstrings — feel each vertebra decompressing as you roll down.',
    cues:['Intentional spinal flexion — controlled mobility drill','Roll down vertebra by vertebra','Only for healthy spines and very light weight','More mobility than strength work'],
    yt:'jefferson curl form tutorial' },

  // ── Shoulders ──────────────────────────────────────────────────────────────
  { id:'ex051', name:'Overhead Press',              muscle:'Shoulders',   movement:'push',  equipment:'Barbell',
    feel:'Front and side delts driving the bar — feel the whole shoulder working, with the side delt and tricep demanding more at lockout.',
    cues:['Bar starts at clavicle / upper chest','Press straight up — bar passes in front of face','Ribs down — don\'t hyperextend lower back','Lock out fully at top'],
    yt:'overhead press form tutorial' },
  { id:'ex052', name:'Dumbbell Shoulder Press',     muscle:'Shoulders',   movement:'push',  equipment:'Dumbbell',
    feel:'All three delt heads — primarily front and side. Feel the shoulder working without chest involvement.',
    cues:['Dumbbells at ear height to start','Press straight up, slight arc inward at top','Don\'t fully lock out — keep tension on delts','Seated version reduces cheating'],
    yt:'dumbbell shoulder press form tutorial' },
  { id:'ex053', name:'Arnold Press',                muscle:'Shoulders',   movement:'push',  equipment:'Dumbbell',
    feel:'A rotating burn through all three delt heads — feel each head being hit as the movement rotates from front-facing to overhead.',
    cues:['Start with palms facing you at chin height','Rotate palms outward as you press up','Adds rotation that hits all three delt heads','Slower and more controlled than regular press'],
    yt:'arnold press form tutorial' },
  { id:'ex054', name:'Machine Shoulder Press',      muscle:'Shoulders',   movement:'push',  equipment:'Machine',
    feel:'Front and side delts cleanly — the fixed path removes stabiliser demand so you feel just the delts pressing.',
    cues:['Adjust seat height — handles at shoulder level','Don\'t arch aggressively — ribs down','Controlled negative on each rep','Good beginner option with stable path'],
    yt:'machine shoulder press form' },
  { id:'ex055', name:'Smith Machine Press',         muscle:'Shoulders',   movement:'push',  equipment:'Machine',
    feel:'Front and medial delts — clean isolation with the fixed bar path removing most lateral stabilisation.',
    cues:['Can press in front or behind neck — in front safer','Fixed bar path — less stabilizer demand','Good for overloading shoulders safely','Adjust body position so bar tracks vertically'],
    yt:'smith machine shoulder press form' },
  { id:'ex056', name:'Lateral Raise',               muscle:'Shoulders',   movement:'push',  equipment:'Dumbbell',
    feel:'Side (medial) delt only — burning sensation on the outer side of the shoulder as you raise. If you feel traps, the weight is too heavy.',
    cues:['Lead with elbows, not hands','Slight forward lean isolates medial delt','Raise to just above shoulder height','Pinky slightly higher than thumb at peak'],
    yt:'lateral raise form tutorial' },
  { id:'ex057', name:'Cable Lateral Raise',         muscle:'Shoulders',   movement:'push',  equipment:'Cable',
    feel:'Medial delt with constant tension — feel it even at the start of the movement unlike dumbbells which start easy.',
    cues:['Cable provides constant tension through full range','Cross body or same-side cable both work','Same cues as dumbbell lateral raise','Great for drop sets'],
    yt:'cable lateral raise form tutorial' },
  { id:'ex058', name:'Machine Lateral Raise',       muscle:'Shoulders',   movement:'push',  equipment:'Machine',
    feel:'Pure medial delt — feel only the lateral head of the shoulder pressing out against the pads with no trap involvement.',
    cues:['Align elbow pad with shoulder joint','Push pads up — don\'t shrug','Squeeze at top, controlled negative','Very safe option for heavy lateral work'],
    yt:'machine lateral raise form' },
  { id:'ex059', name:'Front Raise',                 muscle:'Shoulders',   movement:'push',  equipment:'Dumbbell',
    feel:'Front (anterior) delt burning as you raise — you should feel nothing in the upper trap.',
    cues:['Lift to eye / shoulder height — not higher','Avoid swinging or using momentum','Slight bend in elbow','Works anterior (front) delt primarily'],
    yt:'front raise form tutorial' },
  { id:'ex060', name:'Cable Front Raise',           muscle:'Shoulders',   movement:'push',  equipment:'Cable',
    feel:'Anterior delt with constant cable tension — feel the front of your shoulder pulling the weight up from the very start.',
    cues:['Constant tension unlike dumbbells','Cable behind you, raise to eye level','Keep torso stable — don\'t rock back','One arm at a time for better isolation'],
    yt:'cable front raise form tutorial' },
  { id:'ex061', name:'Upright Row',                 muscle:'Shoulders',   movement:'pull',  equipment:'Barbell',
    feel:'Medial delts and upper traps together — feel both the side of your shoulder and the top of the neck/trap area as elbows rise.',
    cues:['Wide grip reduces impingement risk','Elbows lead and drive high','Don\'t pull above chin level','Some shoulder structures don\'t tolerate this well'],
    yt:'upright row form tutorial' },
  { id:'ex062', name:'Barbell Shrug',               muscle:'Shoulders',   movement:'push',  equipment:'Barbell',
    feel:'Upper traps only — a squeezing contraction at the top of your shoulder and neck as you shrug straight up.',
    cues:['Shrug straight up — no rolling forward or back','Pause and squeeze at top for 1 second','Full hang at bottom for stretch','Heavy straps optional'],
    yt:'barbell shrug form tutorial' },
  { id:'ex063', name:'Dumbbell Shrug',              muscle:'Shoulders',   movement:'push',  equipment:'Dumbbell',
    feel:'Upper trap contraction — feel the muscle between your ears and shoulder blades squeezing hard at the peak.',
    cues:['Same cues as barbell shrug','Dumbbells at sides allow more natural path','Slight pause at top — feel the trap contraction','Don\'t roll shoulders'],
    yt:'dumbbell shrug form tutorial' },
  { id:'ex064', name:'Bradford Press',              muscle:'Shoulders',   movement:'push',  equipment:'Barbell',
    feel:'Continuous shoulder burn across all three delt heads — they fatigue quickly with the constant alternating motion.',
    cues:['Alternate front and back press in one fluid motion','Don\'t full lockout — keep bar moving','High volume shoulder workout','Light weight — this is conditioning focused'],
    yt:'bradford press form tutorial' },
  { id:'ex065', name:'Cuban Press',                 muscle:'Shoulders',   movement:'push',  equipment:'Dumbbell',
    feel:'Rear delt and external rotators — feel the back of the shoulder and rotation muscles working, especially during the external rotation phase.',
    cues:['Three-part movement: upright row → external rotate → press','Great for shoulder health and external rotator strength','Use very light weight','Slow and controlled throughout'],
    yt:'cuban press form tutorial' },
  { id:'ex066', name:'Behind The Neck Press',       muscle:'Shoulders',   movement:'push',  equipment:'Barbell',
    feel:'Full delt engagement — especially medial and rear heads as the bar pushes the shoulder into a wide overhead position.',
    cues:['Requires good shoulder mobility — assess first','Press from behind-neck to overhead','Lower slowly — don\'t bounce at bottom','Not recommended if you have shoulder issues'],
    yt:'behind neck press form tutorial' },
  { id:'ex067', name:'Push Press',                  muscle:'Shoulders',   movement:'push',  equipment:'Barbell',
    feel:'Leg drive transferring into shoulder lockout — feel the momentum load into the delts as you lock out overhead.',
    cues:['Dip knees slightly, then drive up with legs to initiate','Transfer leg power into the bar','Press arms to lockout overhead','More weight than strict press — power movement'],
    yt:'push press form tutorial' },

  // ── Biceps ─────────────────────────────────────────────────────────────────
  { id:'ex068', name:'Barbell Curl',                muscle:'Biceps',      movement:'pull',  equipment:'Barbell',
    feel:'Full bicep from stretch to peak — a pulling sensation in the bicep from hang to full curl, squeeze hardest at the top.',
    cues:['Elbows pinned at sides — don\'t swing','Curl to full contraction at top','Full extension at bottom — don\'t cut range','Straight bar may strain wrists — try EZ bar'],
    yt:'barbell curl form tutorial' },
  { id:'ex069', name:'Dumbbell Curl',               muscle:'Biceps',      movement:'pull',  equipment:'Dumbbell',
    feel:'Bicep peak contraction — feel the bicep squeeze hardest as you supinate (rotate pinky up) at the top of the curl.',
    cues:['Supinate wrist as you curl up (rotate pinky up)','Elbows stay at your sides throughout','Lower with control — slow negative','Alternate arms or both together'],
    yt:'dumbbell curl form tutorial' },
  { id:'ex070', name:'Cable Curl',                  muscle:'Biceps',      movement:'pull',  equipment:'Cable',
    feel:'Constant bicep tension throughout — feel the cable pulling even at the very bottom where dumbbells feel easy.',
    cues:['Cable provides constant tension through full range','Keep elbows at sides','Curl to full contraction','Great for peak bicep squeeze'],
    yt:'cable curl form tutorial' },
  { id:'ex071', name:'Hammer Curl',                 muscle:'Biceps',      movement:'pull',  equipment:'Dumbbell',
    feel:'Brachialis (under the bicep) and forearms — feel the thickness through the outer bicep and forearm more than the peak.',
    cues:['Neutral grip (thumbs up) throughout — don\'t supinate','Hits brachialis and brachioradialis more than regular curl','Curl to shoulder, elbows stay pinned','Builds arm thickness'],
    yt:'hammer curl form tutorial' },
  { id:'ex072', name:'Incline Dumbbell Curl',       muscle:'Biceps',      movement:'pull',  equipment:'Dumbbell',
    feel:'Long head of the bicep under stretch — a pulling sensation at the top of the arm as it hangs behind your torso.',
    cues:['Incline puts long head bicep under greater stretch','Arms hang behind torso at bottom','Pure bicep isolation — no swing possible','Use lighter weight than standing curls'],
    yt:'incline dumbbell curl form tutorial' },
  { id:'ex073', name:'Concentration Curl',          muscle:'Biceps',      movement:'pull',  equipment:'Dumbbell',
    feel:'Isolated peak contraction — feel only the bicep working with zero shoulder involvement. Strong squeeze at the very top.',
    cues:['Elbow braced against inner thigh','Full extension at bottom, full squeeze at top','Twist wrist (supinate) as you curl','Slow and deliberate — peak contraction focus'],
    yt:'concentration curl form tutorial' },
  { id:'ex074', name:'Preacher Curl',               muscle:'Biceps',      movement:'pull',  equipment:'Barbell',
    feel:'Lower bicep insertion working fully — feel the bicep across its entire range with the pad eliminating any swing.',
    cues:['Upper arms flat on preacher pad throughout','Don\'t hyperextend at the bottom','Full contraction at top','Eliminates swing — isolates bicep'],
    yt:'preacher curl form tutorial' },
  { id:'ex075', name:'Spider Curl',                 muscle:'Biceps',      movement:'pull',  equipment:'Barbell',
    feel:'Strong bicep peak and constant tension — gravity hits the bicep from a different angle, feel the peak contraction intensely at the top.',
    cues:['Lie prone on incline bench, arms hang down','Arms stay perpendicular to floor throughout','Gravity provides resistance from a different angle','Great peak bicep isolation'],
    yt:'spider curl form tutorial' },
  { id:'ex076', name:'Zottman Curl',                muscle:'Biceps',      movement:'pull',  equipment:'Dumbbell',
    feel:'Bicep on the way up, forearm extensor on the way down — feel a clear switch in the working muscle as you rotate at the top.',
    cues:['Curl up with supinated grip (palms up)','Rotate to pronated at top (palms down)','Lower slowly in pronated position — trains forearm extensors','Rotate back at bottom to repeat'],
    yt:'zottman curl form tutorial' },
  { id:'ex077', name:'Cross Body Curl',             muscle:'Biceps',      movement:'pull',  equipment:'Dumbbell',
    feel:'Outer bicep and brachialis — feel the pulling sensation toward the outer side of the upper arm.',
    cues:['Curl across body toward opposite shoulder','Neutral/hammer grip throughout','Emphasises brachialis and outer bicep','Alternate arms'],
    yt:'cross body curl form tutorial' },
  { id:'ex078', name:'Resistance Band Curl',        muscle:'Biceps',      movement:'pull',  equipment:'Band',
    feel:'Bicep tension increasing as you curl — feel the band getting harder at the top where you should squeeze most.',
    cues:['Stand on middle of band','Curl both handles up together or alternating','Band tension increases as you curl — hardest at top','Great travel or home option'],
    yt:'resistance band curl form tutorial' },
  { id:'ex079', name:'EZ Bar Curl',                 muscle:'Biceps',      movement:'pull',  equipment:'Barbell',
    feel:'Bicep from a slightly pronated position — similar to barbell curl but often more comfortable at the wrist and elbow.',
    cues:['Angled grip reduces wrist/elbow strain','Same cues as barbell curl','Keep elbows pinned at sides','Often more comfortable than straight bar'],
    yt:'ez bar curl form tutorial' },
  { id:'ex080', name:'Reverse Curl',                muscle:'Biceps',      movement:'pull',  equipment:'Barbell',
    feel:'Brachioradialis and forearm extensors — feel it on the top of the forearm and the outside of the upper arm, not the bicep peak.',
    cues:['Pronated grip (palms down)','Emphasises brachioradialis and forearms','Elbows stay at sides','Harder than regular curl — use lighter weight'],
    yt:'reverse curl form tutorial' },
  { id:'ex081', name:'21s',                         muscle:'Biceps',      movement:'pull',  equipment:'Barbell',
    feel:'Exhaustive burn through three distinct zones of the bicep — feel the tension in the bottom range, mid range, and peak separately.',
    cues:['7 reps bottom half (hang to 90°), 7 reps top half (90° to top), 7 full reps','Constant tension throughout','High volume — use lighter weight than normal','No rest between the three mini-sets'],
    yt:'21s bicep curl form tutorial' },

  // ── Triceps ────────────────────────────────────────────────────────────────
  { id:'ex082', name:'Tricep Pushdown',             muscle:'Triceps',     movement:'push',  equipment:'Cable',
    feel:'Tricep lockout at the bottom — feel the back of the upper arm engage fully only when you extend to full lockout.',
    cues:['Elbows pinned at sides — don\'t let them move','Extend to full lockout','Control the return — don\'t let cable pull arms up','Keep wrists straight'],
    yt:'tricep pushdown form tutorial' },
  { id:'ex083', name:'Rope Pushdown',               muscle:'Triceps',     movement:'push',  equipment:'Cable',
    feel:'Lateral and medial tricep heads — flaring the rope at the bottom adds an extra squeeze through the outer tricep.',
    cues:['Split rope apart at bottom for full contraction','Elbows stay pinned to sides','Flare handles outward at lockout','More tricep isolation than bar pushdown'],
    yt:'rope pushdown form tutorial' },
  { id:'ex084', name:'Skull Crusher',               muscle:'Triceps',     movement:'push',  equipment:'Barbell',
    feel:'Long head of the tricep under stretch — feel the back of the upper arm working hardest as the bar lowers toward your forehead.',
    cues:['Lower bar to forehead or above head on bench','Elbows stay pointing up — don\'t flare','Full extension at top without locking elbows','Have a spotter for heavy sets'],
    yt:'skull crusher form tutorial' },
  { id:'ex085', name:'Overhead Tricep Extension',   muscle:'Triceps',     movement:'push',  equipment:'Dumbbell',
    feel:'Long head of the tricep fully stretched overhead — a pulling sensation at the back of the upper arm at the bottom position.',
    cues:['Arms overhead — puts long head under maximal stretch','Elbows point forward, not flared to sides','Lower dumbbell behind head slowly','Extend fully at top'],
    yt:'overhead tricep extension form tutorial' },
  { id:'ex086', name:'Close Grip Bench Press',      muscle:'Triceps',     movement:'push',  equipment:'Barbell',
    feel:'Tricep primarily — pressing sensation through the back of the arm and inner chest; shoulder stays much quieter than regular bench.',
    cues:['Grip shoulder width — don\'t go too narrow','Elbows track close to torso throughout','Full range like regular bench','Tricep and chest involvement'],
    yt:'close grip bench press form tutorial' },
  { id:'ex087', name:'Tricep Kickback',             muscle:'Triceps',     movement:'push',  equipment:'Dumbbell',
    feel:'Pure tricep lockout — feel the back of the arm contract hard as you extend the arm straight back. Hold the contraction.',
    cues:['Hinge forward, upper arm parallel to floor','Extend arm back to full lockout','Hold contraction for 1 second at top','Don\'t swing — controlled throughout'],
    yt:'tricep kickback form tutorial' },
  { id:'ex088', name:'Tricep Dips',                 muscle:'Triceps',     movement:'push',  equipment:'Bodyweight',
    feel:'Tricep pressing your body up — staying upright shifts away from chest. Feel the back of the arm working throughout.',
    cues:['Stay upright — don\'t lean forward (that targets chest)','Elbows track backward, not flared','Lower until elbows at ~90°','Lock out fully at top'],
    yt:'tricep dips form tutorial' },
  { id:'ex089', name:'Overhead Cable Extension',    muscle:'Triceps',     movement:'push',  equipment:'Cable',
    feel:'Long head of the tricep stretching and contracting — similar to overhead DB extension but with constant cable tension throughout.',
    cues:['Rope above head, face away from cable','Lean slightly forward at hips','Extend arms overhead to full lockout','Elbows stay narrow throughout'],
    yt:'overhead cable extension form tutorial' },
  { id:'ex090', name:'EZ Bar Skull Crusher',        muscle:'Triceps',     movement:'push',  equipment:'Barbell',
    feel:'Back of the upper arm — same feel as skull crusher but the angled grip is often more comfortable at the elbow joint.',
    cues:['Same as skull crusher but more wrist-friendly','Lower to forehead or above head','Full extension at top','Go slightly lighter than barbell version'],
    yt:'ez bar skull crusher form tutorial' },
  { id:'ex091', name:'Single Arm Pushdown',         muscle:'Triceps',     movement:'push',  equipment:'Cable',
    feel:'Tricep isolation one side at a time — feel any strength imbalance between arms through the full lockout.',
    cues:['One arm at a time for symmetry','Elbow stays pinned at side','Full lockout at bottom','Rotate palm outward at lockout for extra squeeze'],
    yt:'single arm tricep pushdown form' },
  { id:'ex092', name:'Bench Dips',                  muscle:'Triceps',     movement:'push',  equipment:'Bodyweight',
    feel:'Triceps pressing your bodyweight — feel the back of the arm working. The further your feet, the harder the tricep works.',
    cues:['Hands on bench behind you, legs extended','Lower body until elbows at 90°','Don\'t go deeper than comfortable for shoulders','Elevate feet to increase difficulty'],
    yt:'bench dips form tutorial' },

  // ── Quads ──────────────────────────────────────────────────────────────────
  { id:'ex093', name:'Barbell Squat',               muscle:'Quads',       movement:'squat', equipment:'Barbell',
    feel:'Quads burning on the way up, glutes squeezing at lockout — feel the front of the thigh working, especially just above the knee.',
    cues:['Chest up, slight forward lean is normal','Knees track over toes — push them out','Squat to hip crease below knee depth','Drive through whole foot, not just heels'],
    yt:'barbell squat form tutorial' },
  { id:'ex094', name:'Front Squat',                 muscle:'Quads',       movement:'squat', equipment:'Barbell',
    feel:'Quads heavily — more upright torso means the front of the thigh takes almost all the load, especially burning above the knee.',
    cues:['Elbows high — don\'t let them drop','More upright torso than back squat','Quad dominant — great for knee health','Requires wrist and thoracic mobility'],
    yt:'front squat form tutorial' },
  { id:'ex095', name:'Goblet Squat',                muscle:'Quads',       movement:'squat', equipment:'Dumbbell',
    feel:'Quads and inner thighs — the wide-elbow cue opens the hips so you feel the inner quad and adductor engage together.',
    cues:['Hold dumbbell or kettlebell at chest','Elbows between knees at bottom — pushes knees out','Great for learning squat pattern','Upright torso naturally achieved'],
    yt:'goblet squat form tutorial' },
  { id:'ex096', name:'Leg Press',                   muscle:'Quads',       movement:'squat', equipment:'Machine',
    feel:'Quads as knees lower toward chest; more glutes if feet are higher. Burning sensation in the front of the thighs throughout.',
    cues:['Don\'t lock out knees at top','Feet shoulder width, toes slightly out','Full range — bring knees toward chest','Don\'t let lower back peel off pad'],
    yt:'leg press form tutorial' },
  { id:'ex097', name:'Hack Squat',                  muscle:'Quads',       movement:'squat', equipment:'Machine',
    feel:'Quad dominant — feel the front of the thigh burning especially in the lower quad near the knee as you drive up.',
    cues:['Shoulders under pads, back against pad','Feet position affects quad vs glute emphasis','Lower until thighs past parallel if mobile','Don\'t lockout — keep tension'],
    yt:'hack squat form tutorial' },
  { id:'ex098', name:'Leg Extension',               muscle:'Quads',       movement:'squat', equipment:'Machine',
    feel:'Quads only — a burning squeeze directly in the front of the thigh at full extension. No glute or hamstring involvement at all.',
    cues:['Adjust so knee joint aligns with machine pivot','Extend to full lockout — squeeze quads','Control the descent — don\'t let weight crash','Isolation movement — high reps work well'],
    yt:'leg extension form tutorial' },
  { id:'ex099', name:'Lunge',                       muscle:'Quads',       movement:'squat', equipment:'Dumbbell',
    feel:'Quad burn in the front leg driving you back up; glute squeeze at the top of each rep.',
    cues:['Step forward — front knee tracks over toes','Back knee lowers toward floor without touching','Keep torso upright throughout','Step back, then repeat other leg'],
    yt:'lunge form tutorial' },
  { id:'ex100', name:'Bulgarian Split Squat',       muscle:'Quads',       movement:'squat', equipment:'Dumbbell',
    feel:'Quad and glute of the front leg — one of the deepest single-leg burns achievable. Feel it right through the front thigh and glute.',
    cues:['Rear foot elevated on bench','Front foot far enough forward — front shin stays vertical','Lower until back knee near floor','Most demanding single-leg quad exercise'],
    yt:'bulgarian split squat form tutorial' },
  { id:'ex101', name:'Step Up',                     muscle:'Quads',       movement:'squat', equipment:'Dumbbell',
    feel:'Front leg quad and glute only — feel the work in just the stepping leg, not the push-off from the back foot.',
    cues:['Step full foot onto box — don\'t push off back foot','Drive through front heel to stand','Control the descent — step back slowly','Box height = knee height or slightly lower'],
    yt:'step up exercise form tutorial' },
  { id:'ex102', name:'Smith Machine Squat',         muscle:'Quads',       movement:'squat', equipment:'Machine',
    feel:'Quads with feet forward, more balanced with feet under bar — burning in the front of the thigh throughout.',
    cues:['Position feet slightly in front of bar — not under it','Bar path is fixed — adjust stance accordingly','Same depth cues as barbell squat','Good for beginners or rehab'],
    yt:'smith machine squat form tutorial' },
  { id:'ex103', name:'Sissy Squat',                 muscle:'Quads',       movement:'squat', equipment:'Bodyweight',
    feel:'Extreme quad isolation — a burning stretch in the front of the thigh as the knee travels far forward. Intense and direct.',
    cues:['Hold support — heels elevated on plate','Lean back as knees come forward past toes','Extreme quad isolation','Not for beginners or those with knee issues'],
    yt:'sissy squat form tutorial' },
  { id:'ex104', name:'Wall Sit',                    muscle:'Quads',       movement:'squat', equipment:'Bodyweight',
    feel:'Burning isometric contraction in the quads — feel both legs burning around the kneecap area as you hold the position.',
    cues:['Back flat against wall','Thighs parallel to floor, knees at 90°','Hold position — isometric burn','Great for muscle endurance'],
    yt:'wall sit form tutorial' },
  { id:'ex105', name:'Box Jump',                    muscle:'Quads',       movement:'squat', equipment:'Bodyweight',
    feel:'Explosive quad and glute power — feel the hips and quads loading before the jump, an explosive release at takeoff.',
    cues:['Quarter squat before jump — load hips and quads','Land softly with bent knees on box','Step down — don\'t jump down','Focus on power, not height'],
    yt:'box jump form tutorial' },
  { id:'ex106', name:'Sled Push',                   muscle:'Quads',       movement:'squat', equipment:'Machine',
    feel:'Quads and glutes driving you forward — feel the whole leg working with each powerful step.',
    cues:['Low body position, drive forward with legs','Short powerful steps','Arms fully extended on handles','Great for quad strength without eccentric stress'],
    yt:'sled push form tutorial' },
  { id:'ex107', name:'Pause Squat',                 muscle:'Quads',       movement:'squat', equipment:'Barbell',
    feel:'Quads fully loaded in the pause with no bounce to help — feel the bottom position tension demanding more from the front of the thigh.',
    cues:['Pause 2–3 seconds at bottom of squat','No relaxing at bottom — stay braced','Eliminates elastic rebound from tendons','Builds true bottom strength'],
    yt:'pause squat form tutorial' },
  { id:'ex108', name:'Heel Elevated Squat',         muscle:'Quads',       movement:'squat', equipment:'Barbell',
    feel:'Even more front-of-thigh burn than flat-footed squat — elevated heels allow the knee to travel further forward, loading the quad more.',
    cues:['Heels on plates or wedge board','Reduces ankle mobility demands','More quad dominant than flat footed squat','Good beginner modification'],
    yt:'heel elevated squat form tutorial' },
  { id:'ex109', name:'Zercher Squat',               muscle:'Quads',       movement:'squat', equipment:'Barbell',
    feel:'Quads and core together — quad burn similar to front squat, plus the core bracing to prevent forward collapse under the bar.',
    cues:['Bar held in crook of elbows at chest','Elbows stay close together','Forces upright torso — great for core and quads','Uncomfortable initially — use sleeve or towel'],
    yt:'zercher squat form tutorial' },
  { id:'ex110', name:'Cossack Squat',               muscle:'Quads',       movement:'squat', equipment:'Bodyweight',
    feel:'Quad of the bending leg and inner thigh (adductor) of the straight leg — feel a deep lateral quad stretch going down.',
    cues:['Squat to one side while other leg extends straight','Heel of extended leg can stay down or lift','Great hip mobility drill and lateral strength','Work both sides equally'],
    yt:'cossack squat form tutorial' },
  { id:'ex111', name:'Pistol Squat',                muscle:'Quads',       movement:'squat', equipment:'Bodyweight',
    feel:'Quad and glute of the working leg under your full bodyweight — an intense single-leg quad burn through the entire range.',
    cues:['Single leg squat to full depth','Extended leg straight out in front','Balance challenge + quad strength combined','Build up with assisted versions first'],
    yt:'pistol squat form tutorial' },
  { id:'ex112', name:'Jump Squat',                  muscle:'Quads',       movement:'squat', equipment:'Bodyweight',
    feel:'Explosive quad and calf — feel the power generating from the quads and hips before the jump, calves adding the final push.',
    cues:['Quarter to half squat then explode up','Land softly — absorb through hips and knees','Develops power and explosiveness','High impact — not for knee issues'],
    yt:'jump squat form tutorial' },
  { id:'ex113', name:'Bodyweight Squat',            muscle:'Quads',       movement:'squat', equipment:'Bodyweight',
    feel:'Quads from the ground up — feel the front of the thigh working as you stand, glutes squeezing at full lockout.',
    cues:['Same cues as barbell squat without load','Perfect to learn the movement pattern','Arms out front for counterbalance','Depth first — weight can come later'],
    yt:'bodyweight squat form tutorial' },
  { id:'ex114', name:'Reverse Lunge',               muscle:'Quads',       movement:'squat', equipment:'Dumbbell',
    feel:'Front leg quad and glute — stepping back reduces knee stress; feel the same front-leg drive as the forward lunge.',
    cues:['Step backward — easier on knees than forward lunge','Front knee stays over ankle','Lower back knee toward floor','Less balance challenge than walking lunge'],
    yt:'reverse lunge form tutorial' },
  { id:'ex115', name:'Walking Lunge',               muscle:'Quads',       movement:'squat', equipment:'Dumbbell',
    feel:'Quads and glutes alternating with each step — feel the continuous burn building through both legs over the set.',
    cues:['Continuous forward movement','Each step: knee tracks over toes','Keep torso upright','Challenges balance and coordination'],
    yt:'walking lunge form tutorial' },
  { id:'ex116', name:'Landmine Squat',              muscle:'Quads',       movement:'squat', equipment:'Barbell',
    feel:'Quads and upper back — similar feel to goblet squat; front of the thigh burns as you drive up.',
    cues:['Hold end of landmine bar at chest height','More upright torso than barbell squat','Less spinal loading option','Good for those with shoulder mobility issues'],
    yt:'landmine squat form tutorial' },

  // ── Hamstrings ─────────────────────────────────────────────────────────────
  { id:'ex117', name:'Lying Leg Curl',              muscle:'Hamstrings',  movement:'hinge', equipment:'Machine',
    feel:'Back of the thigh curling — feel the hamstring squeeze as your heel approaches your glute, hardest in the last few degrees.',
    cues:['Align knee joint with machine pivot point','Curl to full contraction — heel to glute','Don\'t let hips rise off pad','Slow controlled negative'],
    yt:'lying leg curl form tutorial' },
  { id:'ex118', name:'Seated Leg Curl',             muscle:'Hamstrings',  movement:'hinge', equipment:'Machine',
    feel:'Hamstrings under more stretch than lying — feel the pull all the way up the back of the thigh from knee to glute.',
    cues:['Greater range of motion than lying version','Knee joint aligned with machine axis','Full contraction, full extension each rep','Hamstrings under more stretch when seated'],
    yt:'seated leg curl form tutorial' },
  { id:'ex119', name:'Nordic Curl',                 muscle:'Hamstrings',  movement:'hinge', equipment:'Bodyweight',
    feel:'Eccentric hamstring strain — feel the hamstrings working desperately to slow your descent. One of the most intense hamstring sensations possible.',
    cues:['Feet anchored, lower body toward floor by extending knees','Eccentric (lowering) is the key — resist with hamstrings','Use hands to push off floor at bottom','Very demanding — start with assisted version'],
    yt:'nordic curl form tutorial' },
  { id:'ex120', name:'Stiff Leg Deadlift',          muscle:'Hamstrings',  movement:'hinge', equipment:'Barbell',
    feel:'Hamstring stretch going down; hamstrings and lower back firing on the way up — feel the pull behind the thigh and just under the glute.',
    cues:['Legs nearly straight — slight knee bend ok','Hip hinge: push hips back as bar lowers','Feel the hamstring stretch at bottom','Keep back flat throughout'],
    yt:'stiff leg deadlift form tutorial' },
  { id:'ex121', name:'Single Leg Deadlift',         muscle:'Hamstrings',  movement:'hinge', equipment:'Dumbbell',
    feel:'Hamstring of the standing leg — feel the stretch as you hinge forward, and the contraction as you return to upright.',
    cues:['Balance on one leg — hinge at hip','Opposite leg extends back as torso tips forward','Maintain level hips — don\'t rotate open','Great for balance and unilateral hamstring strength'],
    yt:'single leg deadlift form tutorial' },
  { id:'ex122', name:'Glute Ham Raise',             muscle:'Hamstrings',  movement:'hinge', equipment:'Machine',
    feel:'Full hamstring contraction — feel the stretch at full extension and a very hard curl contraction at the top.',
    cues:['Feet secured, knees on pad','Extend body, then curl hamstrings to raise up','One of the most demanding hamstring exercises','Control descent fully — don\'t drop'],
    yt:'glute ham raise form tutorial' },
  { id:'ex123', name:'Cable Pull Through',          muscle:'Hamstrings',  movement:'hinge', equipment:'Cable',
    feel:'Hamstrings and glutes — feel the hamstrings loaded as hips push back, glutes squeezing as you stand tall.',
    cues:['Cable between legs, face away from stack','Hip hinge pattern — push hips back','Squeeze glutes and hamstrings to stand','Lighter weight hip hinge practice'],
    yt:'cable pull through form tutorial' },
  { id:'ex124', name:'Sled Pull',                   muscle:'Hamstrings',  movement:'hinge', equipment:'Machine',
    feel:'Hamstrings pulling you backward — feel the back of the thigh engaged with each backward step.',
    cues:['Face the sled, pull with bent-leg rowing motion','Or face away, push through heels','Low impact — great for hamstring conditioning','Eccentric-free: less soreness'],
    yt:'sled pull hamstring form tutorial' },

  // ── Glutes ─────────────────────────────────────────────────────────────────
  { id:'ex125', name:'Hip Thrust',                  muscle:'Glutes',      movement:'hinge', equipment:'Barbell',
    feel:'Glutes almost exclusively — if you feel it in your lower back instead, tuck your pelvis and squeeze your glutes harder at the top.',
    cues:['Upper back on bench, feet flat on floor','Drive hips up — squeeze glutes hard at top','Don\'t hyperextend lower back — neutral at top','Pad the bar for comfort on hips'],
    yt:'hip thrust form tutorial' },
  { id:'ex126', name:'Glute Bridge',                muscle:'Glutes',      movement:'hinge', equipment:'Bodyweight',
    feel:'Glute squeeze at the top — feel your glutes pressing your hips upward. Nothing should be felt in the lower back.',
    cues:['Lie on back, feet flat, knees bent','Drive hips up squeezing glutes','Hold 1–2 seconds at top','Simpler version of hip thrust — floor based'],
    yt:'glute bridge form tutorial' },
  { id:'ex127', name:'Cable Kickback',              muscle:'Glutes',      movement:'hinge', equipment:'Cable',
    feel:'Top of the glute and outer hip — feel the glute squeeze at full extension behind you, not the lower back.',
    cues:['Ankle attachment, face the cable stack','Kick leg backward and up — squeeze glute at top','Keep torso stable — don\'t rotate','Control the return'],
    yt:'cable glute kickback form tutorial' },
  { id:'ex128', name:'Abductor Machine',            muscle:'Glutes',      movement:'push',  equipment:'Machine',
    feel:'Outer glute (glute medius) and outer hip — feel the side of the hip and outer thigh as legs spread.',
    cues:['Sit upright, knees against pads','Push knees outward against resistance','Squeeze glutes and outer hips at peak','Controlled return — don\'t let knees slam in'],
    yt:'abductor machine form tutorial' },
  { id:'ex129', name:'Adductor Machine',            muscle:'Glutes',      movement:'pull',  equipment:'Machine',
    feel:'Inner thighs (adductors) — feel the squeeze along the inner leg as your knees come together.',
    cues:['Sit upright, push knees inward','Squeeze inner thighs at peak contraction','Controlled return — resist the opening'],
    yt:'adductor machine form tutorial' },
  { id:'ex130', name:'Donkey Kick',                 muscle:'Glutes',      movement:'hinge', equipment:'Bodyweight',
    feel:'Glute of the kicking leg — feel the squeeze at the top of the kick. If you feel your lower back, you\'re going too high.',
    cues:['On hands and knees','Kick one leg up and back — bend knee at 90°','Squeeze glute hard at top','Don\'t rotate hips to cheat range'],
    yt:'donkey kick form tutorial' },
  { id:'ex131', name:'Fire Hydrant',                muscle:'Glutes',      movement:'push',  equipment:'Bodyweight',
    feel:'Glute medius (upper outer glute) — feel the side of your hip working, not the hip flexor or lower back.',
    cues:['On hands and knees','Lift knee out to the side like a dog at a hydrant','Keep hips level — don\'t tilt','Targets glute medius'],
    yt:'fire hydrant exercise form tutorial' },
  { id:'ex132', name:'Reverse Hyper',               muscle:'Glutes',      movement:'hinge', equipment:'Machine',
    feel:'Glutes as legs rise; a decompression sensation in the lower back — feel the glute squeeze at the top of the swing.',
    cues:['Hips at edge of pad, legs hang down','Swing legs up and back — glute squeeze at top','Decompresses the lumbar spine','Great accessory for back health'],
    yt:'reverse hyperextension form tutorial' },
  { id:'ex133', name:'Hip Abduction',               muscle:'Glutes',      movement:'push',  equipment:'Cable',
    feel:'Outer glute and hip abductors — feel the side of the hip pulling the leg out against the cable.',
    cues:['Ankle attachment, cable at low pulley','Swing leg out to side against resistance','Brace on something for balance','Targets glute medius — important for hip stability'],
    yt:'cable hip abduction form tutorial' },
  { id:'ex134', name:'Sumo Walk',                   muscle:'Glutes',      movement:'push',  equipment:'Band',
    feel:'Outer glute and hip abductors fighting the band — feel your glutes working to keep your knees from caving inward.',
    cues:['Band above knees, wide stance','Take small lateral steps keeping band taut','Don\'t let knees cave inward','Great warm-up for lower body sessions'],
    yt:'band sumo walk form tutorial' },

  // ── Calves ─────────────────────────────────────────────────────────────────
  { id:'ex135', name:'Standing Calf Raise',         muscle:'Calves',      movement:'push',  equipment:'Machine',
    feel:'Gastrocnemius (outer calf) — full stretch at the bottom, hard squeeze high on the calf at the top. Hold the top for a second.',
    cues:['Full stretch at bottom — heel below platform','Rise to full tiptoe at top','Pause at top for maximum contraction','Slow tempo — calves respond to time under tension'],
    yt:'standing calf raise form tutorial' },
  { id:'ex136', name:'Seated Calf Raise',           muscle:'Calves',      movement:'push',  equipment:'Machine',
    feel:'Soleus (deeper, lower calf) — seated position shifts the work lower compared to standing. A different area of the calf burns.',
    cues:['Targets soleus (deeper calf muscle) with knee bent','Same stretch and squeeze cues as standing version','Full range every rep','Soleus responds to higher reps'],
    yt:'seated calf raise form tutorial' },
  { id:'ex137', name:'Donkey Calf Raise',           muscle:'Calves',      movement:'push',  equipment:'Bodyweight',
    feel:'Gastrocnemius with extra stretch — feel a deeper pull at the bottom due to the forward hip hinge position.',
    cues:['Hinge forward at hips, hands on something stable','Greater gastrocnemius stretch than standing version','Full stretch, full squeeze each rep','Add weight on hips for progression'],
    yt:'donkey calf raise form tutorial' },
  { id:'ex138', name:'Single Leg Calf Raise',       muscle:'Calves',      movement:'push',  equipment:'Bodyweight',
    feel:'Full calf of the working leg — feel any strength imbalance between legs. The burn at the top should be hard to hold.',
    cues:['One foot on edge of step','Other leg crossed behind or held up','Full stretch at bottom, full raise at top','Harder than double-leg — great for imbalances'],
    yt:'single leg calf raise form tutorial' },
  { id:'ex139', name:'Leg Press Calf Raise',        muscle:'Calves',      movement:'push',  equipment:'Machine',
    feel:'Calf working against a heavy load — feel the push through the ball of the foot, full calf contraction at the top.',
    cues:['Push with ball of foot — not toes','Full plantar flexion at top','Controlled return to full dorsiflexion','Can go heavy safely on this version'],
    yt:'leg press calf raise form tutorial' },

  // ── Core ───────────────────────────────────────────────────────────────────
  { id:'ex140', name:'Plank',                       muscle:'Core',        movement:'core',  equipment:'Bodyweight',
    feel:'Deep core tension — feel your abs bracing tight as if about to be punched. A building burn after 20–30 seconds.',
    cues:['Forearms down, body straight line head to heels','Squeeze abs, glutes, quads all at once','Don\'t let hips sag or pike up','Breathe normally — don\'t hold breath'],
    yt:'plank form tutorial' },
  { id:'ex141', name:'Ab Wheel Rollout',            muscle:'Core',        movement:'core',  equipment:'Bodyweight',
    feel:'Deep core bracing — feel your abs fighting to stop your back from arching as you roll out. Stop where you feel the back start to give.',
    cues:['Start on knees — advance to standing when ready','Roll out until hips want to drop','Pull back using abs — not arms','One of the most demanding core exercises'],
    yt:'ab wheel rollout form tutorial' },
  { id:'ex142', name:'Cable Crunch',                muscle:'Core',        movement:'core',  equipment:'Cable',
    feel:'Rectus abdominis — feel the crunch in your abs, not a hip hinge. Pull with the abs, not the arms or shoulders.',
    cues:['Kneel facing cable stack','Pull elbows to thighs — crunch, don\'t hip flex','Round upper back to contract abs','Keep hips in place throughout'],
    yt:'cable crunch form tutorial' },
  { id:'ex143', name:'Crunch',                      muscle:'Core',        movement:'core',  equipment:'Bodyweight',
    feel:'Upper abs contracting — feel the rectus abdominis shortening at the top, a direct squeeze in the belly.',
    cues:['Only lift shoulder blades off floor — small range','Don\'t pull on neck with hands','Exhale as you crunch up','Slow, controlled — squeeze abs at top'],
    yt:'crunch form tutorial' },
  { id:'ex144', name:'Leg Raise',                   muscle:'Core',        movement:'core',  equipment:'Bodyweight',
    feel:'Lower abs and hip flexors — feel the lower belly working to control the legs, especially during the slow lowering phase.',
    cues:['Lie flat, press lower back into floor','Raise legs to 90°, lower slowly','Don\'t let lower back arch off floor','Keep legs straight or slightly bent'],
    yt:'leg raise form tutorial' },
  { id:'ex145', name:'Russian Twist',               muscle:'Core',        movement:'core',  equipment:'Bodyweight',
    feel:'Obliques and transverse abdominis — feel the sides of your midsection rotating and bracing with each twist.',
    cues:['Lean back slightly, feet raised or on floor','Rotate torso side to side — not just arms','Touch the floor beside hip each side','Add weight to increase difficulty'],
    yt:'russian twist form tutorial' },
  { id:'ex146', name:'Hanging Leg Raise',           muscle:'Core',        movement:'core',  equipment:'Bodyweight',
    feel:'Lower abs and hip flexors — feel the lower belly pulling the legs up, and the grip and lats holding you steady on the bar.',
    cues:['Dead hang from bar to start','Raise legs to parallel or higher','Avoid swinging — control the movement','Bent knee version easier than straight leg'],
    yt:'hanging leg raise form tutorial' },
  { id:'ex147', name:'Side Plank',                  muscle:'Core',        movement:'core',  equipment:'Bodyweight',
    feel:'Obliques — feel the side of your waist bracing hard to stop your hips from dropping toward the floor.',
    cues:['Forearm on floor, body in straight line','Hips don\'t sag — squeeze obliques and glutes','Stack feet or stagger for stability','Breathe normally throughout hold'],
    yt:'side plank form tutorial' },
  { id:'ex148', name:'Dead Bug',                    muscle:'Core',        movement:'core',  equipment:'Bodyweight',
    feel:'Deep core and transverse abdominis — the lower back pressed flat into the floor is the sensation to chase throughout.',
    cues:['Press lower back firmly into floor throughout','Opposite arm and leg extend slowly','Move only as far as you can keep back flat','Exhale as you extend'],
    yt:'dead bug exercise form tutorial' },
  { id:'ex149', name:'Pallof Press',                muscle:'Core',        movement:'core',  equipment:'Cable',
    feel:'Obliques resisting rotation — feel your entire midsection bracing to stop the cable from pulling you sideways.',
    cues:['Cable at chest height, stand perpendicular','Press arms straight out — resist rotation','Hold for 2 seconds extended','Anti-rotation exercise — core stability focus'],
    yt:'pallof press form tutorial' },
  { id:'ex150', name:'V Up',                        muscle:'Core',        movement:'core',  equipment:'Bodyweight',
    feel:'Rectus abdominis from both ends — feel the centre of your abs being pulled from top and bottom simultaneously.',
    cues:['Legs and arms raise simultaneously to meet','Full body contracts like a "V" shape','Lower with control — don\'t crash down','Demanding — build up from crunches + leg raises'],
    yt:'v up exercise form tutorial' },
  { id:'ex151', name:'Bicycle Crunch',              muscle:'Core',        movement:'core',  equipment:'Bodyweight',
    feel:'Obliques and rectus abdominis — feel the rotation through your side abs as opposite shoulder and knee meet.',
    cues:['Rotate shoulder (not elbow) to opposite knee','Legs pedal alternately — fully extend each one','Slow and controlled — not a speed exercise','Targets obliques and rectus abdominis'],
    yt:'bicycle crunch form tutorial' },
  { id:'ex152', name:'Dragon Flag',                 muscle:'Core',        movement:'core',  equipment:'Bodyweight',
    feel:'Full core under eccentric load — feel every core muscle fighting to keep your body rigid as you lower.',
    cues:['Hold bench behind head, body straight','Lower as a unit — don\'t pike at hips','Only upper back stays on bench','One of the hardest bodyweight core exercises'],
    yt:'dragon flag form tutorial' },
  { id:'ex153', name:'Hollow Hold',                 muscle:'Core',        movement:'core',  equipment:'Bodyweight',
    feel:'Deep core and hip flexors — a low-grade but real tension through the entire midsection maintaining the curved position.',
    cues:['Lower back pressed into floor','Arms and legs extended low to floor','Body in slight "banana" curve','Foundation of gymnastics core work'],
    yt:'hollow hold form tutorial' },
  { id:'ex154', name:'L Sit',                       muscle:'Core',        movement:'core',  equipment:'Bodyweight',
    feel:'Hip flexors and abs compressing together — feel the hip flexors pulling legs up and the core bracing to hold them horizontal.',
    cues:['Legs straight, parallel to floor','Arms straight, pressing down into dip bars or floor','Compress hip flexors and abs hard','Build up from tucked version'],
    yt:'l sit form tutorial' },
  { id:'ex155', name:'Toe Touch',                   muscle:'Core',        movement:'core',  equipment:'Bodyweight',
    feel:'Upper abs — feel the crunch in the upper belly as you reach upward. Short range but intense contraction.',
    cues:['Legs up to 90°, reach hands toward feet','Only shoulders lift — not full crunch','Short range but intense ab contraction','Don\'t pull on neck'],
    yt:'toe touch crunch form tutorial' },
  { id:'ex156', name:'Flutter Kick',                muscle:'Core',        movement:'core',  equipment:'Bodyweight',
    feel:'Lower abs and hip flexors — feel the lower belly working to keep legs low and the back pressed flat.',
    cues:['Lie flat, legs a few inches off floor','Alternate kicking legs up and down','Lower back stays pressed down','Great for hip flexors and lower abs'],
    yt:'flutter kick form tutorial' },
  { id:'ex157', name:'Mountain Climber',            muscle:'Core',        movement:'core',  equipment:'Bodyweight',
    feel:'Core stability under movement — feel your abs bracing to keep the plank position as legs drive in and out.',
    cues:['Plank position throughout','Drive knees to chest alternately','Don\'t let hips rise or bounce','Great cardio-core combination'],
    yt:'mountain climber form tutorial' },
  { id:'ex158', name:'Wood Chop',                   muscle:'Core',        movement:'core',  equipment:'Cable',
    feel:'Obliques and rotational core — feel the side muscles working as you rotate, not the arms doing the pulling.',
    cues:['Rotate from hips and torso — not just arms','High to low or low to high variations','Keep arms straight','Trains rotational core strength'],
    yt:'cable wood chop form tutorial' },
  { id:'ex159', name:'Landmine Rotation',           muscle:'Core',        movement:'core',  equipment:'Barbell',
    feel:'Obliques and deep core rotating — feel the midsection driving the arc, with arms just guiding.',
    cues:['Hold end of landmine bar with both hands','Arc bar side to side — rotate from core','Arms stay extended throughout','Controlled speed — not momentum'],
    yt:'landmine rotation form tutorial' },

  // ── Cardio ─────────────────────────────────────────────────────────────────
  { id:'ex160', name:'Treadmill',                   muscle:'Cardio',      movement:'cardio',equipment:'Machine',
    feel:'Legs and lungs — calves, quads and glutes working together; aim to hold a pace where you can barely hold a conversation.',
    cues:['Don\'t hold the rails — use natural arm swing','Land midfoot, not heel striking','Incline 1–2% to simulate outdoor running','Breathe rhythmically with stride'],
    yt:'treadmill running form tutorial' },
  { id:'ex161', name:'Cycling',                     muscle:'Cardio',      movement:'cardio',equipment:'Machine',
    feel:'Quads and cardiovascular system — feel the legs pumping and heart rate rising. Push and pull the pedals in full circles.',
    cues:['Seat height so knee has slight bend at bottom of pedal stroke','Don\'t pedal just with quads — think circles','Engage core to stabilise upper body','Vary resistance for intervals'],
    yt:'stationary bike form tutorial' },
  { id:'ex162', name:'Rowing Machine',              muscle:'Cardio',      movement:'cardio',equipment:'Machine',
    feel:'Full body burn — legs on the drive, back when leaning, arms at the finish. Legs should be doing about 60% of the work.',
    cues:['Drive order: legs → lean back → arms pull','Recovery order: arms → lean forward → legs','Keep back straight — not rounded','Ratio: 1 pull to 2 recovery'],
    yt:'rowing machine form tutorial' },
  { id:'ex163', name:'Jump Rope',                   muscle:'Cardio',      movement:'cardio',equipment:'Bodyweight',
    feel:'Calves, shoulders and cardiovascular system — feel the bounce from the balls of the feet and wrists rotating the rope.',
    cues:['Stay on balls of feet — not flat footed','Small jumps — just enough to clear rope','Wrists do the rotating — not arms','Rhythm first, speed later'],
    yt:'jump rope form tutorial' },
  { id:'ex164', name:'Stair Climber',               muscle:'Cardio',      movement:'cardio',equipment:'Machine',
    feel:'Glutes and quads — feel each step pushing through the whole leg, especially the glute on each push down.',
    cues:['Don\'t lean on rails — stands upright','Full step: push through whole foot','Glutes and quads both engage','Set pace you can sustain for duration'],
    yt:'stair climber form tutorial' },
  { id:'ex165', name:'Elliptical',                  muscle:'Cardio',      movement:'cardio',equipment:'Machine',
    feel:'Legs and cardiovascular system with low impact — feel the push-pull through both legs and handles, smooth and controlled.',
    cues:['Push and pull handles to engage upper body','Keep stride smooth — avoid bouncing','Upright posture — don\'t hunch','Low impact — good for joint health'],
    yt:'elliptical form tutorial' },
  { id:'ex166', name:'Battle Ropes',                muscle:'Cardio',      movement:'cardio',equipment:'Bodyweight',
    feel:'Shoulders, arms and core — feel the shoulder burn come on fast; core bracing to keep the waves consistent.',
    cues:['Athletic stance — knees slightly bent','Alternating waves: one arm up as other goes down','Drive from shoulders and core','Intensity determines wave amplitude'],
    yt:'battle ropes form tutorial' },
  { id:'ex167', name:'Burpee',                      muscle:'Cardio',      movement:'cardio',equipment:'Bodyweight',
    feel:'Full body cardiovascular — feel the intensity build quickly across all muscle groups and in your breathing rate.',
    cues:['Jump feet back to plank — perform push-up optional','Jump feet to hands','Explode up with arms overhead','Scale difficulty by removing jump or push-up'],
    yt:'burpee form tutorial' },
  { id:'ex168', name:'Box Jump',                    muscle:'Cardio',      movement:'cardio',equipment:'Bodyweight',
    feel:'Quads and glutes generating explosive power — feel the load in the hips and quads on takeoff, absorb through the whole leg on landing.',
    cues:['Load hips before jumping — not just calves','Land softly with bent knees','Step down — don\'t jump down — to save joints','Start with a lower box'],
    yt:'box jump form tutorial' },
  { id:'ex169', name:'Assault Bike',                muscle:'Cardio',      movement:'cardio',equipment:'Machine',
    feel:'Full body cardiovascular — arms and legs both burning together. Intensity is brutal and immediate.',
    cues:['Push and pull handles — full body effort','Sit upright, drive from hips','Brutal for intervals — work to rest ratio matters','All-out sprints or steady state both effective'],
    yt:'assault bike form tutorial' },
  { id:'ex170', name:'Ski Erg',                     muscle:'Cardio',      movement:'cardio',equipment:'Machine',
    feel:'Lats, triceps and core pulling down — feel the back and arms working together with each pull while the core stays braced.',
    cues:['Pull handles down from overhead to thighs','Hinge at hips as you pull — not just arms','Reset arms overhead quickly','Great upper body cardio with core demand'],
    yt:'ski erg form tutorial' },
  { id:'ex171', name:'Sled Drag',                   muscle:'Cardio',      movement:'cardio',equipment:'Machine',
    feel:'Hamstrings and glutes pulling backward — feel the back of the leg loading with each backward step.',
    cues:['Lean back slightly, walk backward','Drive through heels, feel hamstrings working','Keep back tall — don\'t round','Low eccentric stress — great for recovery cardio'],
    yt:'sled drag form tutorial' },

  // ── Olympic / Power ────────────────────────────────────────────────────────
  { id:'ex172', name:'Power Clean',                 muscle:'Full Body',   movement:'hinge', equipment:'Barbell',
    feel:'Explosive hip extension through the whole posterior chain — feel the hips snap through, then the catch absorb in the front rack.',
    cues:['Pull bar close to body from floor','Explosive hip extension — shrug, then catch','Catch in quarter-squat on front of shoulders','Technical movement — learn with light weight first'],
    yt:'power clean form tutorial' },
  { id:'ex173', name:'Hang Clean',                  muscle:'Full Body',   movement:'hinge', equipment:'Barbell',
    feel:'Hip snap and front rack catch — similar to power clean but without the long pull from the floor.',
    cues:['Start from hang (mid-thigh or knee level)','Explosive hip extension into a pull and catch','Elbows shoot forward fast on catch','Easier starting position than floor clean'],
    yt:'hang clean form tutorial' },
  { id:'ex174', name:'Clean and Jerk',              muscle:'Full Body',   movement:'hinge', equipment:'Barbell',
    feel:'Full body sequence — legs in the clean, then shoulder and tricep lockout in the jerk overhead.',
    cues:['Clean phase first, then jerk overhead','Dip and drive with legs for the jerk','Split stance or squat under bar overhead','Most technically demanding barbell lift'],
    yt:'clean and jerk form tutorial' },
  { id:'ex175', name:'Snatch',                      muscle:'Full Body',   movement:'hinge', equipment:'Barbell',
    feel:'Massive hip and lat power in one movement — feel the explosive hip drive sending the bar overhead in a single pull.',
    cues:['Wide grip, bar overhead in one movement','Huge hip extension, then drop under bar','Most technical Olympic lift — need coaching','Learn hang snatch before full version'],
    yt:'snatch form tutorial Olympic weightlifting' },
  { id:'ex176', name:'Hang Snatch',                 muscle:'Full Body',   movement:'hinge', equipment:'Barbell',
    feel:'Hip snap and overhead stability — feel the hip extension launch the bar, then the shoulder locking out overhead.',
    cues:['Wide grip, start at hang position','Explosive hip extension, pull bar high','Drop under bar and lock out overhead','Simpler than full snatch from floor'],
    yt:'hang snatch form tutorial' },
  { id:'ex177', name:'Power Snatch',                muscle:'Full Body',   movement:'hinge', equipment:'Barbell',
    feel:'Hip explosion and overhead catch in a quarter squat — feel the pull and overhead stability without a deep squat.',
    cues:['Catch bar overhead in quarter squat — not full squat','Wide grip throughout','All the explosive power of snatch, less mobility needed','Good entry point to snatch variations'],
    yt:'power snatch form tutorial' },

  // ── Full Body / Compound ───────────────────────────────────────────────────
  { id:'ex178', name:'Kettlebell Swing',            muscle:'Full Body',   movement:'hinge', equipment:'Kettlebell',
    feel:'Glutes and hamstrings snapping into extension — the bell floats from hip power. Feel the posterior chain, not the shoulders.',
    cues:['Hip hinge — not a squat','Explosive hip snap drives the bell','Arms are just a pendulum — power from hips','Bell floats up from hip power, not arm lift'],
    yt:'kettlebell swing form tutorial' },
  { id:'ex179', name:'Thruster',                    muscle:'Full Body',   movement:'squat', equipment:'Barbell',
    feel:'Quad drive from the squat feeding directly into shoulder lockout — feel both muscles working as one continuous movement.',
    cues:['Front squat + overhead press in one movement','Drive out of squat and use momentum to press','Bar on front of shoulders during squat','High demand — common in CrossFit'],
    yt:'thruster form tutorial' },
  { id:'ex180', name:'Man Maker',                   muscle:'Full Body',   movement:'push',  equipment:'Dumbbell',
    feel:'Everything burning — chest, back, shoulders, legs and heart rate all elevated simultaneously.',
    cues:['Push-up + row + row + stand + curl + press','One continuous movement flow','Light dumbbells — this is conditioning','Demanding full body cardiovascular exercise'],
    yt:'man maker exercise form tutorial' },
  { id:'ex181', name:'Turkish Get Up',              muscle:'Full Body',   movement:'core',  equipment:'Kettlebell',
    feel:'Shoulder stability and total body coordination — feel the shoulder pressing the bell up the entire time while the rest of the body moves around it.',
    cues:['Eye stays on bell throughout entire movement','Sequence: roll → press → leg sweep → lunge → stand','Reverse to come back down','Learn the steps separately before combining'],
    yt:'turkish get up form tutorial' },
  { id:'ex182', name:'Farmers Walk',                muscle:'Full Body',   movement:'carry', equipment:'Dumbbell',
    feel:'Grip, traps and core — feel the forearms working to hold the weight, traps bracing, and core preventing any side lean.',
    cues:['Grip tight, shoulders packed back and down','Tall posture — don\'t lean to either side','Steady steps, controlled pace','Great for grip, traps, and core stability'],
    yt:'farmers walk form tutorial' },
  { id:'ex183', name:'Sandbag Clean',               muscle:'Full Body',   movement:'hinge', equipment:'Bodyweight',
    feel:'Hip drive and core — similar to barbell clean but the awkward load forces more core engagement throughout.',
    cues:['Awkward load — more core demand than barbell','Hip hinge and pull similar to barbell clean','Land softly, absorb through legs','Great real-world strength builder'],
    yt:'sandbag clean form tutorial' },
  { id:'ex184', name:'Tire Flip',                   muscle:'Full Body',   movement:'hinge', equipment:'Bodyweight',
    feel:'Posterior chain explosion — feel the glutes and hips driving the flip, transitioning to a chest push at the top.',
    cues:['Get low — deadlift the tire, don\'t squat under it','Explosively extend hips','Push tire up when it\'s at chest level','Grip on inside edge of tire'],
    yt:'tire flip form tutorial' },

  // ── Forearms ───────────────────────────────────────────────────────────────
  { id:'ex185', name:'Wrist Curl',                  muscle:'Forearms',    movement:'pull',  equipment:'Barbell',
    feel:'Inner forearm (flexors) — feel the front of your forearm from wrist to elbow contracting as you curl up.',
    cues:['Forearms on thighs or bench — wrists hang off edge','Curl wrists upward slowly','Full extension at bottom — don\'t cut range','High reps work well for forearms'],
    yt:'wrist curl form tutorial' },
  { id:'ex186', name:'Reverse Wrist Curl',          muscle:'Forearms',    movement:'push',  equipment:'Barbell',
    feel:'Top of the forearm (extensors) — feel the back of the forearm working, a very different sensation from regular wrist curls.',
    cues:['Pronated grip (palms down)','Lift wrists upward against gravity','Slower movement — extensors are weaker than flexors','Use lighter weight than wrist curl'],
    yt:'reverse wrist curl form tutorial' },
  { id:'ex187', name:'Wrist Roller',                muscle:'Forearms',    movement:'pull',  equipment:'Bodyweight',
    feel:'Both sides of the forearm alternately — feel flexors and extensors burning as the weight rolls up and down.',
    cues:['Arms extended at shoulder height','Roll weight up by alternating wrist turns','Control as weight lowers — don\'t just let it fall','Both directions work different muscles'],
    yt:'wrist roller form tutorial' },
  { id:'ex188', name:'Plate Pinch',                 muscle:'Forearms',    movement:'carry', equipment:'Plate',
    feel:'Fingertip tendons and thumb — feel the pinch grip working at the tips of the fingers and the base of the thumb.',
    cues:['Pinch two plates smooth side out between fingers and thumb','Hold for time — don\'t rest on thigh','Builds crushing and pinch grip','Progress weight or duration over time'],
    yt:'plate pinch grip form tutorial' },

  // ── Neck ───────────────────────────────────────────────────────────────────
  { id:'ex189', name:'Neck Curl',                   muscle:'Neck',        movement:'pull',  equipment:'Plate',
    feel:'Front of the neck (sternocleidomastoid) — feel the front neck muscles contracting as you lift your head forward.',
    cues:['Lie face up on bench, head off edge','Hold plate on forehead, flex neck forward','Very light weight — neck is delicate','Slow, controlled movement only'],
    yt:'neck curl form tutorial' },
  { id:'ex190', name:'Neck Extension',              muscle:'Neck',        movement:'push',  equipment:'Plate',
    feel:'Back of the neck and upper traps — feel the muscles at the back of the skull and neck contracting as you extend.',
    cues:['Lie face down, head off bench edge','Hold plate on back of head','Extend neck backward slowly','Light weight, high reps, slow pace'],
    yt:'neck extension form tutorial' },
  { id:'ex191', name:'Neck Lateral Flexion',        muscle:'Neck',        movement:'pull',  equipment:'Bodyweight',
    feel:'Side of the neck — feel the muscle from your ear toward your collarbone contracting as you tilt your head.',
    cues:['Tilt ear toward shoulder — against hand resistance','Gentle movement — no jerking','Work both sides equally','Can also use light plate for resistance'],
    yt:'neck lateral flexion form tutorial' },

  // ── Stretching / Mobility ──────────────────────────────────────────────────
  { id:'ex192', name:'Hip Flexor Stretch',          muscle:'Mobility',    movement:'core',  equipment:'Bodyweight',
    feel:'Front of the hip joint (iliopsoas) — feel the stretch at the very front of the hip, not the lower back.',
    cues:['Kneeling lunge position','Push hips forward — feel front of hip stretch','Keep pelvis tucked — don\'t arch lower back','Hold 30–60 seconds each side'],
    yt:'hip flexor stretch tutorial' },
  { id:'ex193', name:'Pigeon Pose',                 muscle:'Mobility',    movement:'core',  equipment:'Bodyweight',
    feel:'Deep in the outer hip and glute — feel the stretch in the external rotators and piriformis of the front leg.',
    cues:['Front leg at 90° or more — feel it in external rotators','Fold forward for deeper stretch','Breathe into the tightness','Hold 1–2 minutes per side'],
    yt:'pigeon pose tutorial' },
  { id:'ex194', name:'World Greatest Stretch',      muscle:'Mobility',    movement:'core',  equipment:'Bodyweight',
    feel:'Hip flexor, hamstring and thoracic spine all opening — feel three different stretches cycling through with each rep.',
    cues:['Lunge forward, same arm inside foot','Reach up with opposite arm to sky','Opens hip, thoracic spine, and hamstring','5 reps per side as a warm-up'],
    yt:'world greatest stretch tutorial' },
  { id:'ex195', name:'Cat Cow',                     muscle:'Mobility',    movement:'core',  equipment:'Bodyweight',
    feel:'The whole spine moving sequentially — feel each vertebra participating in the wave from tailbone to neck.',
    cues:['On hands and knees — wrists under shoulders','Cat: round spine toward ceiling (exhale)','Cow: arch spine, chest forward (inhale)','Slow breathing with movement — 10 reps'],
    yt:'cat cow stretch tutorial' },
  { id:'ex196', name:'Thoracic Rotation',           muscle:'Mobility',    movement:'core',  equipment:'Bodyweight',
    feel:'Mid-back (thoracic spine) opening — feel the rotation in your middle back specifically, not the lower back or hips.',
    cues:['Lie on side, knees stacked at 90°','Rotate top arm across body and open to sky','Keep hips stacked — only spine rotates','Hold open position briefly before returning'],
    yt:'thoracic rotation stretch tutorial' },
  { id:'ex197', name:'Ankle Mobility Drill',        muscle:'Mobility',    movement:'core',  equipment:'Bodyweight',
    feel:'Calf and ankle joint — feel the stretch at the back of the ankle and lower calf as the knee tracks forward.',
    cues:['Knee over toe, rock forward without heel rising','Touch knee to wall for consistency','10 reps per side','Critical for squat and lunge mechanics'],
    yt:'ankle mobility drill tutorial' },
  { id:'ex198', name:'90 90 Hip Stretch',           muscle:'Mobility',    movement:'core',  equipment:'Bodyweight',
    feel:'Deep hip external and internal rotators — feel the hip socket being mobilised in both directions across the two legs.',
    cues:['Both hips at 90° — front and back legs','Sit tall, not slumped','Can lean forward over front leg for deeper work','Targets both internal and external hip rotation'],
    yt:'90 90 hip stretch tutorial' },
  { id:'ex199', name:'Couch Stretch',               muscle:'Mobility',    movement:'core',  equipment:'Bodyweight',
    feel:'The deepest hip flexor and quad stretch — feel the pull at the very front of the hip joint and up through the rectus femoris.',
    cues:['Back foot up against wall, knee on floor','Bring torso upright — feel deep hip flexor stretch','Squeeze glute of the stretched side','Most effective hip flexor stretch available'],
    yt:'couch stretch tutorial' },
  { id:'ex200', name:'Foam Rolling',                muscle:'Mobility',    movement:'core',  equipment:'Bodyweight',
    feel:'Pressure release in tight tissue — look for tender spots and hold on them. The "good pain" release sensation is what you\'re after.',
    cues:['Roll slowly — 1 inch per second','Pause on tight spots for 5–10 seconds','Avoid rolling directly on joints','Do before stretching for best effect'],
    yt:'foam rolling form tutorial' },
]

export function getExerciseById(id) {
  return EXERCISES.find(e => e.id === id) || null
}

export function searchExercises(query, limit = 20) {
  if (!query || !query.trim()) return EXERCISES.slice(0, limit)
  const q = query.toLowerCase()
  return EXERCISES
    .filter(e =>
      e.name.toLowerCase().includes(q) ||
      e.muscle.toLowerCase().includes(q) ||
      e.equipment.toLowerCase().includes(q)
    )
    .slice(0, limit)
}

// Alternates kept in a separate map so exercise objects stay clean
const ALTERNATES = {
  ex001:['ex002','ex003','ex004'], ex002:['ex001','ex005'],       ex003:['ex001','ex004'],
  ex004:['ex001','ex003'],         ex005:['ex002','ex003'],       ex006:['ex001','ex003'],
  ex007:['ex006','ex003'],         ex008:['ex009','ex010'],       ex009:['ex008','ex010'],
  ex010:['ex008','ex009'],         ex011:['ex001','ex003'],       ex012:['ex001','ex003'],
  ex013:['ex008','ex009'],         ex014:['ex001','ex004'],       ex015:['ex008'],
  ex016:['ex008'],                 ex017:['ex010'],               ex018:['ex002','ex005'],
  ex019:['ex004'],                 ex020:['ex004'],

  ex021:['ex022','ex023'],         ex022:['ex021','ex024'],       ex023:['ex021'],
  ex024:['ex021','ex022'],         ex025:['ex026','ex027'],       ex026:['ex025','ex027'],
  ex027:['ex025','ex026'],         ex028:['ex027','ex025'],       ex029:['ex027'],
  ex030:['ex031','ex032'],         ex031:['ex030','ex032'],       ex032:['ex030','ex031'],
  ex033:['ex031','ex030'],         ex034:['ex031'],               ex035:['ex032','ex030'],
  ex036:['ex032','ex030'],         ex037:['ex038'],               ex038:['ex037'],
  ex039:['ex027'],                 ex040:['ex021'],               ex041:['ex021'],
  ex042:['ex021'],                 ex043:['ex022'],               ex044:['ex043'],
  ex045:['ex022'],                 ex046:['ex025','ex030'],       ex047:['ex037','ex038'],
  ex048:['ex031','ex032'],         ex049:['ex032'],               ex050:['ex022'],

  ex051:['ex052','ex053'],         ex052:['ex051','ex053'],       ex053:['ex052','ex051'],
  ex054:['ex051','ex052'],         ex055:['ex051'],               ex056:['ex057','ex058'],
  ex057:['ex056'],                 ex058:['ex056','ex057'],       ex059:['ex060'],
  ex060:['ex059'],                 ex061:['ex056'],               ex062:['ex063'],
  ex063:['ex062'],                 ex064:['ex051'],               ex065:['ex052'],
  ex066:['ex051'],                 ex067:['ex051'],

  ex068:['ex069','ex070'],         ex069:['ex068','ex070'],       ex070:['ex068','ex069'],
  ex071:['ex069'],                 ex072:['ex069','ex068'],       ex073:['ex069'],
  ex074:['ex068','ex070'],         ex075:['ex068'],               ex076:['ex069','ex071'],
  ex077:['ex071'],                 ex078:['ex069'],               ex079:['ex068'],
  ex080:['ex068'],                 ex081:['ex068'],

  ex082:['ex083','ex084'],         ex083:['ex082'],               ex084:['ex082','ex085'],
  ex085:['ex082','ex084'],         ex086:['ex084','ex082'],       ex087:['ex082'],
  ex088:['ex082','ex084'],         ex089:['ex085','ex082'],       ex090:['ex084'],
  ex091:['ex082'],                 ex092:['ex088'],

  ex093:['ex094','ex095'],         ex094:['ex093','ex095'],       ex095:['ex093','ex096'],
  ex096:['ex093','ex095'],         ex097:['ex093','ex096'],       ex098:['ex096'],
  ex099:['ex093','ex100'],         ex100:['ex099','ex093'],       ex101:['ex099'],
  ex102:['ex093','ex096'],         ex103:['ex098'],               ex104:['ex096'],
  ex105:['ex093'],                 ex106:['ex096'],               ex107:['ex093'],
  ex108:['ex093','ex094'],         ex109:['ex093'],               ex110:['ex099','ex100'],
  ex111:['ex100'],                 ex112:['ex105','ex093'],       ex113:['ex093','ex095'],
  ex114:['ex099'],                 ex115:['ex099'],               ex116:['ex095'],

  ex117:['ex118','ex022'],         ex118:['ex117'],               ex119:['ex117'],
  ex120:['ex022','ex117'],         ex121:['ex022','ex120'],       ex122:['ex119','ex117'],
  ex123:['ex022'],                 ex124:['ex117'],

  ex125:['ex126','ex127'],         ex126:['ex125'],               ex127:['ex125','ex126'],
  ex128:['ex127'],                 ex129:['ex127'],               ex130:['ex126'],
  ex131:['ex128'],                 ex132:['ex125'],               ex133:['ex128'],
  ex134:['ex128'],

  ex135:['ex136','ex137'],         ex136:['ex135'],               ex137:['ex135'],
  ex138:['ex135'],                 ex139:['ex135'],

  ex140:['ex141','ex142'],         ex141:['ex140'],               ex142:['ex143'],
  ex143:['ex142','ex144'],         ex144:['ex143'],               ex145:['ex143'],
  ex146:['ex144'],                 ex147:['ex140'],               ex148:['ex140'],
  ex149:['ex140'],                 ex150:['ex143'],               ex151:['ex143'],
  ex152:['ex141'],                 ex153:['ex140'],               ex154:['ex140'],
  ex155:['ex143'],                 ex156:['ex144'],               ex157:['ex140'],
  ex158:['ex145'],                 ex159:['ex158'],

  ex160:['ex161','ex162'],         ex161:['ex160','ex163'],       ex162:['ex160','ex161'],
  ex163:['ex160'],                 ex164:['ex160'],               ex165:['ex160','ex161'],
  ex166:['ex163'],                 ex167:['ex163'],               ex168:['ex167'],
  ex169:['ex161'],                 ex170:['ex162'],               ex171:['ex160'],

  ex172:['ex021'],                 ex173:['ex172'],               ex174:['ex172'],
  ex175:['ex172'],                 ex176:['ex175'],               ex177:['ex175'],

  ex178:['ex125','ex021'],         ex179:['ex093','ex051'],       ex180:['ex167'],
  ex181:['ex140'],                 ex182:['ex062'],               ex183:['ex172'],
  ex184:['ex021'],

  ex185:['ex186'],                 ex186:['ex185'],               ex187:['ex185'],
  ex188:['ex182'],

  ex189:['ex190'],                 ex190:['ex189'],               ex191:['ex189'],
}

export function getAlternates(exerciseId) {
  const ids = ALTERNATES[exerciseId] || []
  return ids.map(id => getExerciseById(id)).filter(Boolean)
}

